int numbers[100];
int left;

int $[foobar: int a]{
    $[hla_stdout_puti32 : a ];
    return 3;
    if ( a > 0 )
        $[foobar : a-1];    
    $[hla_stdout_puti32 : a ];
}
int $[main]{
    $[hla_stdout_puti32 : $[foobar:5] ];
}
/*
int $[main]{
    int a ;
    int b;
    a<-5;
    b<-32;
    $[hla_stdout_puti32 : a ];
    $[hla_stdout_putc : b ];
    do{
        $[hla_stdout_puti32 : a ];
        $[hla_stdout_putc : b ];
        a<-a-1;
    }while( a>0 );
}

*/
